name: ArchGuard 3.0 - CodeDB
on: [ push ]

env:
  plugin:
    registry: https://plugins.archguard.org/
  server:
    url: http://localhost:8084

jobs:
  backend:
    config:
      displayName: Backend

    steps:
      - uses: actions/checkout@0.1.0-SNAPSHOT
        with:
          branch: master

      - uses: analyser/source-code@0.0.1
        with:
          language: kotlin
          features: [ "datamap" ]
          output: ['http', 'json']
          server-url: ${{ env.server.url }}

#      - uses: linter/database@v1
