name: ArchGuard 3.0 - CodeDB
on: [ push ]

env:
  registry:
    url: https://registry.archguard.org/
    local: true
  server:
    url: http://localhost:8084

jobs:
  backend:
    config:
      displayName: Backend

    steps:
      - uses: actions/checkout@0.1.0-SNAPSHOT
        with:
          branch: master

      - uses: analyser/source-code@0.0.1
        with:
          language: kotlin
          features: [ "datamap" ]
          output: [ "json" ]
          server-url: ${{ env.server.url }}
          path: "."
#      - uses: analyser/sca@0.0.1
#        with:
#          path: "."
#      - uses: analyser/estimate@0.0.1
#        with:
#          path: "."
#      - uses: analyser/architecture@0.0.1
#        with:
#          path: "."
#      - uses: analyser/diff_changes@0.0.1
#        with:
#          path: "."

#      - uses: linter/database@v1
#      - used: metric/oo@v1
#      - used: metric/complexity@v1

# for translation custom rules
#      - used: factor/sonarqube@v1
