name: ArchGuard 3.0 - CodeDB
on: [ push ]

env:
  registry:
    url: https://registry.archguard.org/
    local: true
  server:
    url: http://localhost:8084

jobs:
  backend:
    config:
      displayName: Backend

    steps:
#      - uses: actions/checkout@0.1.0-SNAPSHOT
#        with:
#          repository: https://github.com/archguard/code-poc.git
#          branch: master

      - name: "Complexity"
        uses: archguard/scanner@v2
        with:
          type: "estimate"
          path: "."
          output: [ "json" ]

      - name: "Source Code with Linter"
        uses: archguard/scanner@v2
        with:
          type: "source_code"
          language: kotlin
          features: [ "datamap" ]
          output: [ "json" ]
          rules: [ "webapi", "test", "sql" ]
          path: "."

      - name: Software Composition Analysis
        uses: archguard/scanner@v2
        with:
          type: "sca"
          path: "."
          language: kotlin
          output: [ "json" ]

#      - uses: analyser/architecture@0.0.1
#        with:

#      - uses: linter/database@v1
#      - used: metric/oo@v1
#      - used: metric/complexity@v1

# for translation custom rules
#      - used: factor/sonarqube@v1
