name: ArchGuard 3.0 - CodeDB
on: [ push ]
config:
  plugin:
    registry: https://plugins.archguard.org/
  server:
    url: http://localhost:8084

jobs:
  backend:
    config:
      displayName: Backend

    steps:
      - uses: actions/checkout@0.1.0-SNAPSHOT
      - uses: analyser/source-code@0.0.1
        with:
          languages: kotlin
          features: [ "datamap" ]
        output: source-code.json

#      - uses: linter/database@v1
